name: Rainbow
description: Learn the basics of using Material Components by building a simple app with core components.

dependencies:
  flutter:
    sdk: flutter
  flutter_webview_plugin: ^0.3.0+2
  intl: ^0.15.6
  dio: ^2.0.1
  cookie_jar: ^0.0.7
  path_provider: ^0.5.0+1
  image_picker: ^0.5.0+3
  image_cropper: ^1.0.0
  photo_view: ^0.1.3
  flutter_secure_storage: ^3.1.3
  json_annotation: ^2.0.0
  shared_preferences: ^0.5.1+1
  flutter_redux: ^0.5.3
  cupertino_icons: ^0.1.0
  sensors: ^0.4.0+1
  cached_network_image: ^0.6.0+1
  flutter_tags: ^0.1.8
  image_picker_saver: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  native_share:
    path: ../../flutter_plugin/native_share

flutter:
  uses-material-design: true
  assets:
    - assets/diamond.png
    - assets/default-avatar.png
